config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :jobs

  root to: "jobs#index"
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :jobs
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :category

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :jobs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :find_job, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :job_owner, only: [:edit, :update, :destroy]

  def index
    if params[:category].blank?
      @jobs = Job.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @jobs = Job.where(category_id: @category_id).order("created_at DESC")
    end
  end

  def show
  end

  def new
    @job = current_user.jobs.build
  end

  def create
    @job = current_user.jobs.build(jobs_params)

    if @job.save
      redirect_to @job, notice: 'A job was successfully saved!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @job.update(jobs_params)
      redirect_to @job, notice: 'A job was successfully updated!'
    else
      render :edit
    end
  end

  def destroy
    @job.destroy
    redirect_to root_path, notice: 'A job was successfully deleted!'
  end

  private

  def jobs_params
    params.require(:job).permit(:title, :description, :company, :url, :category_id)
  end

  def find_job
    @job = Job.find(params[:id])
  end

  def job_owner
    unless @job.user_id == current_user.id
      flash[:notice] = 'Only owners can edit their Job'
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(content)
		renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
		options = {
			autolink: true,
      no_intra_emphasis: true,
      disable_indented_code_blocks: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
		}
		Redcarpet::Markdown.new(renderer, options).render(content).html_safe
	end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.haml
= simple_form_for(@job, html: { class: 'form-horizontal'}) do |f|
	= f.collection_select :category_id, Category.all, :id, :name, {promt: "Choose a category" }, input_html: { class: "dropdown-toggle" }
	= f.input :title, label: "Job Title", input_html: { class: "form-control" }
	= f.input :description, label: "Job Description", input_html: { class: "form-control" }
	= f.input :company, label: "Your Company", input_html: { class: "form-control" }
	= f.input :url, label: "Link to Job", input_html: { class: "form-control" }
	%br/
	= f.button :submit

app/views/jobs/edit.html.haml
%h1 Edit Job

= render 'form'

= link_to 'Back', root_path

app/views/jobs/index.html.haml
#jobs
  - if @jobs.empty? && !user_signed_in?
    .container
      %p
      Please
      = link_to 'Sign Up', new_user_registration_path
      or
      = link_to 'Sign In', new_user_session_path
      to post a new job!
  - else
    - @jobs.each do |job|
      .job
        %h2= link_to job.title, job
        %p= job.company

app/views/jobs/new.html.haml
%h1 New Job

= render 'form'

= link_to 'Back', root_path

app/views/jobs/show.html.haml
#jobs
  .job
    %h2= @job.title
    %p= markdown @job.description
    %h3= @job.company
    %button.btn.btn-default= link_to 'Apply for Job', @job.url

#links
  - if (user_signed_in? && (current_user.id == @job.user_id))
    = link_to 'Back', root_path, class: "btn btn-sm btn-default"
    = link_to 'Edit', edit_job_path(@job), class: "btn btn-sm btn-default"
    = link_to 'Delete', job_path(@job), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-default"

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %title Jobs Board

  %body
    %nav.navbar.navbar-default
      .container
        .navbar-brand Rails Jobs
        %ul.nav.navbar-nav.navbar-left
          %li= link_to 'All Jobs', root_path
          - Category.all.each do |category|
            %li= link_to category.name, jobs_path(category: category.name)
        %ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            %li= link_to 'New Job', new_job_path, class: "navbar-right navbar-link"
            %li= link_to 'Profile', edit_user_registration_path, class: "navbar-right navbar-link"
            %li= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "navbar-right navbar-link"
          - else
            %li= link_to 'Sign Up', new_user_registration_path, class: "navbar-right navbar-link"
            %li= link_to 'Sign In', new_user_session_path, class: "navbar-right navbar-link"

    .container
      - flash.each do |name, msg|
        = content_tag :div, msg, class: "alert alert-info"
    .container
      .col-md-6.col-md-offset-3
        = yield